name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Build with Buildx Bake (arm64, no cache)
      run: |
        docker buildx bake --no-cache \
          --set "*.platform=linux/arm64"
